"""Phase 2: transcript segments

Revision ID: 1015168ce67f
Revises: 0001
Create Date: 2026-08-16 09:19:55.661748
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1015168ce67f'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('speaker_id', sa.String(length=64), nullable=True),
    sa.Column('avg_logprob', sa.Float(), nullable=True),
    sa.Column('no_speech_prob', sa.Float(), nullable=True),
    sa.Column('compression_ratio', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_segments_speaker_id'), ['speaker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_segments_video_id'), ['video_id'], unique=False)
        batch_op.create_index('ix_transcript_segments_video_position', ['video_id', 'position'], unique=False)
        batch_op.create_index('ix_transcript_segments_video_start', ['video_id', 'start_s'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index('ix_transcript_segments_video_start')
        batch_op.drop_index('ix_transcript_segments_video_position')
        batch_op.drop_index(batch_op.f('ix_transcript_segments_video_id'))
        batch_op.drop_index(batch_op.f('ix_transcript_segments_speaker_id'))

    op.drop_table('transcript_segments')
    # ### end Alembic commands ###
