"""Phase 4: keyframes and OCR blocks

Revision ID: 85aaa61fda82
Revises: 7db29eccb2f6
Create Date: 2026-08-16 13:42:21.808647
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '85aaa61fda82'
down_revision: str | None = '7db29eccb2f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyframes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('time_s', sa.Float(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('phash', sa.String(length=32), nullable=True),
    sa.Column('change', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyframes_video_id'), 'keyframes', ['video_id'], unique=False)
    op.create_index('ix_keyframes_video_position', 'keyframes', ['video_id', 'position'], unique=False)
    op.create_index('ix_keyframes_video_start', 'keyframes', ['video_id', 'start_s'], unique=False)
    op.create_table('ocr_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('keyframe_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['keyframe_id'], ['keyframes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_blocks_keyframe_id'), 'ocr_blocks', ['keyframe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_blocks_keyframe_id'), table_name='ocr_blocks')
    op.drop_table('ocr_blocks')
    op.drop_index('ix_keyframes_video_start', table_name='keyframes')
    op.drop_index('ix_keyframes_video_position', table_name='keyframes')
    op.drop_index(op.f('ix_keyframes_video_id'), table_name='keyframes')
    op.drop_table('keyframes')
    # ### end Alembic commands ###
