"""Phase 5: events and topics

Revision ID: f9cbd1549424
Revises: 8be17b1bb84a
Create Date: 2026-08-16 14:57:08.541402
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f9cbd1549424'
down_revision: str | None = '8be17b1bb84a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_index(op.f('ix_events_video_id'), 'events', ['video_id'], unique=False)
    op.create_index('ix_events_video_start', 'events', ['video_id', 'start_s'], unique=False)
    op.create_index('ix_events_video_type', 'events', ['video_id', 'type'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('boundary_strength', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_parent_id'), 'topics', ['parent_id'], unique=False)
    op.create_index(op.f('ix_topics_video_id'), 'topics', ['video_id'], unique=False)
    op.create_index('ix_topics_video_position', 'topics', ['video_id', 'position'], unique=False)
    op.create_index('ix_topics_video_start', 'topics', ['video_id', 'start_s'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_topics_video_start', table_name='topics')
    op.drop_index('ix_topics_video_position', table_name='topics')
    op.drop_index(op.f('ix_topics_video_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_parent_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index('ix_events_video_type', table_name='events')
    op.drop_index('ix_events_video_start', table_name='events')
    op.drop_index(op.f('ix_events_video_id'), table_name='events')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
