"""Phase 8: collections

Revision ID: 5b11f292e10c
Revises: f9cbd1549424
Create Date: 2026-08-16 15:45:45.925805
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5b11f292e10c'
down_revision: str | None = 'f9cbd1549424'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('videos', sa.Column('collection_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_videos_collection_id'), 'videos', ['collection_id'], unique=False)
    op.create_foreign_key(None, 'videos', 'collections', ['collection_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_index(op.f('ix_videos_collection_id'), table_name='videos')
    op.drop_column('videos', 'collection_id')
    op.drop_table('collections')
    # ### end Alembic commands ###
